name: CI


on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 15 * *'


jobs:
  ci:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install
        run: npx --package mini-cross@0.15.2 mc --no-tty _ composer install

      - name: Test
        run: npx --package mini-cross@0.15.2 mc --no-tty _ vendor/bin/phpunit

